import React from 'react';
import { Target, TrendingUp, DollarSign, Users, Award } from 'lucide-react';

export const BusinessTab: React.FC = () => {
  return (
    <div className="space-y-6">
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2.5 rounded-xl bg-emerald-500/20 text-emerald-400">
            <Target className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-slate-100">Phase 1: Business Understanding</h3>
            <p className="text-xs text-slate-400">Strategic Alignment, Persona Taxonomy & Campaign ROI</p>
          </div>
        </div>

        <p className="text-sm text-slate-300 leading-relaxed mb-6">
          In modern retail and e-commerce, one-size-fits-all marketing generates poor conversion rates and causes high customer churn. 
          The objective of this project is to apply unsupervised machine learning to group <strong>500 customers</strong> into actionable behavioural cohorts (e.g. VIP Champions, Frugal Savers, Trendsetters) to unlock personalized campaigns, increase retention, and optimize lifetime customer value (LTV).
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
            <div className="flex items-center gap-2 text-emerald-400 mb-1">
              <TrendingUp className="w-4 h-4" />
              <span className="text-xs font-semibold uppercase">Campaign ROI</span>
            </div>
            <div className="text-2xl font-bold text-slate-100">3.5x Uplift</div>
            <p className="text-[11px] text-slate-500 mt-1">Via tailored persona promotions</p>
          </div>

          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
            <div className="flex items-center gap-2 text-cyan-400 mb-1">
              <Users className="w-4 h-4" />
              <span className="text-xs font-semibold uppercase">Retention Rate</span>
            </div>
            <div className="text-2xl font-bold text-slate-100">+28% YoY</div>
            <p className="text-[11px] text-slate-500 mt-1">Mitigating high-churn segments</p>
          </div>

          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
            <div className="flex items-center gap-2 text-purple-400 mb-1">
              <DollarSign className="w-4 h-4" />
              <span className="text-xs font-semibold uppercase">VIP Revenue Share</span>
            </div>
            <div className="text-2xl font-bold text-slate-100">54% of Sales</div>
            <p className="text-[11px] text-slate-500 mt-1">Generated by Top 20% tier</p>
          </div>

          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
            <div className="flex items-center gap-2 text-amber-400 mb-1">
              <Award className="w-4 h-4" />
              <span className="text-xs font-semibold uppercase">Inference Speed</span>
            </div>
            <div className="text-2xl font-bold text-slate-100">&lt; 2 ms / query</div>
            <p className="text-[11px] text-slate-500 mt-1">Real-time classification</p>
          </div>
        </div>
      </div>
    </div>
  );
};
